version: '3.8'

services:
  hibernate_postgres:
    image: postgres
    container_name: hibernateDemo
    read_only: true
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=hibernateDb
    expose:
      - "54300"
    ports:
      - "54300:54300"
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    command: -p 54300
volumes:
  postgres-volume: